version: '3.8'

services:
  todolist-api:
    build:
      context: .
      dockerfile: Dockerfile.new
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=TodoListDb;Username=postgres;Password=postgres123
      - Jwt__Issuer=todolist-api
      - Jwt__Audience=todolist-client
      - Jwt__Key=ThisIsAVeryLongSecretKeyThatMeetsTheMinimum256BitRequirementForHS256Algorithm123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
      - Jwt__ExpiryMinutes=120
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todolist-network
    restart: on-failure

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: TodoListDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todolist-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d TodoListDb"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@todolist.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - todolist-network

volumes:
  postgres_data:

networks:
  todolist-network:
    driver: bridge
